version: '3.8'

services:
    postgres:
        image: postgres:14-alpine
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - postgres:/var/lib/postgresql/data:delegated
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
volumes:
    postgres:
