info:
  contact:
    email: giangnguyen.neko.130@gmail.com
    name: Giang Nguyen
    url: https://github.com/kurneo
  description: Golang REST API
  title: Go REST API
  version: "1.0"
paths:
  /api/admin/v1/tags/list:
    get:
      consumes:
      - application/json
      description: Get list tags
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
      security:
      - Bearer: []
      summary: list tags
      tags:
      - Tags
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
